### ISSUE TITLE
Multiclass probability prediction

### ISSUE THREAD

**Issue by mnwright** [benjilu/forestError#4]
Thanks for the package! Do you think it could be extended to multiclass probability predictions? 

We are predicting probabilities for each class and want to have prediction intervals for these probabilities. Example: 

````R
train_idx <- sample(nrow(iris), 2/3 * nrow(iris))
dat_train <- iris[train_idx, ]
dat_test <- iris[-train_idx, ]

rf <- ranger(Species ~ ., dat_train, probability = TRUE)
predict(rf, dat_test)$predictions
````

**Comment by benjilu** [comment]
Sorry for the delayed response. I sent an email back in March to the address listed on your personal website (web@) asking for clarification, but I don't think I got a response. Perhaps it went to your spam folder. (I sent an email instead of directly replying here because there was some possibly relevant context that should probably be kept private for now.) Happy to resend the email if you're still interested in moving this issue forward--just let me know.
